### ISSUE TITLE
Passing of data (can't think of good title)

### ISSUE THREAD

**Issue by brianbodollo** [sourcescript/react-iz#2]
i'm not sure but confident that the test would work properly. I'm not sure because all  the props just passes 'undefined' sorry i can't make it work right now (probably need some guidance though) but soon it will work (this will not take much much time, probably asap). I'm open with your comments regarding to the components-spec.js file

**Comment by srph** [comment]
Please follow the traditional guidelines. Create a branch, and submit your changes as a pull-request.

**Comment by srph** [comment]
I'm sure I advised this. You really need to check other repositories too. If you wanted to create an example, please create an `examples` directory [as shown here](https://github.com/sourcescript/alt-notify/tree/master/examples).

I'll create a pull-request.

As I said, you are trying to pass `this` of what in the `expect`? Your `this` won't automagically point to the **ReactIz** `component`. Have you checked your last project in unit-testing? I'm pretty sure that should you an idea where you are wrong at.

You don't need to change it if it fails or such. You can leave it blank. Again, if you're not sure of your work, please check my comment above.

Anyway, it's cool. I'll just fix what needs fixing.

**Comment by brianbodollo** [comment]
Sorry i forgot that it was a reusable component. My bad i'll figure that this out and fix it.
